// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class Person
    {
        public Guid IdPerson { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Cellphone { get; set; }
        public string Address { get; set; }
        public string Dni { get; set; }
        public string Email { get; set; }
        public DateTime? RegistrationDate { get; set; }
    }
}